//
// Created by Dan Jiang on 2020/4/18.
//

#ifndef ALGORITHMISMYGIRLFRIEND_DATA_STRUCTURE_STRING_H
#define ALGORITHMISMYGIRLFRIEND_DATA_STRUCTURE_STRING_H

void TestDigitToInt();
void TestAlphaToInt();

#endif //ALGORITHMISMYGIRLFRIEND_DATA_STRUCTURE_STRING_H
