//
// Created by Dan Jiang on 2020/5/5.
//

#ifndef ALGORITHMISMYGIRLFRIEND__DATA_STRUCTURE_TREE_H_
#define ALGORITHMISMYGIRLFRIEND__DATA_STRUCTURE_TREE_H_

void TestBinaryTree();
void TestFindKthNodeInBST();

#endif //ALGORITHMISMYGIRLFRIEND__DATA_STRUCTURE_TREE_H_
