//
// Created by Dan Jiang on 2020/4/26.
//

#ifndef ALGORITHMISMYGIRLFRIEND_DATA_STRUCTURE_LINKLIST_H
#define ALGORITHMISMYGIRLFRIEND_DATA_STRUCTURE_LINKLIST_H

void TestListNode();

#endif //ALGORITHMISMYGIRLFRIEND_DATA_STRUCTURE_LINKLIST_H
