//
// Created by Dan Jiang on 2020/4/26.
//

#ifndef ALGORITHMISMYGIRLFRIEND_TIME_EFFICIENCY_H
#define ALGORITHMISMYGIRLFRIEND_TIME_EFFICIENCY_H

void TestFindLongestSeq();

#endif //ALGORITHMISMYGIRLFRIEND_TIME_EFFICIENCY_H
