//
// Created by Dan Jiang on 2020/7/21.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SORTANDFIND_COUNTING_SORT_H_
#define ALGORITHMISMYGIRLFRIEND_SORTANDFIND_COUNTING_SORT_H_

void CountingSort(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SORTANDFIND_COUNTING_SORT_H_
