//
// Created by Dan Jiang on 2020/7/20.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SORTANDFIND_FIND_MAX_KTH_IN_UNSORTED_ARRAY_H_
#define ALGORITHMISMYGIRLFRIEND_SORTANDFIND_FIND_MAX_KTH_IN_UNSORTED_ARRAY_H_

#include "../common.h"

int FindMaxKthInUnsortedArray(int k, int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SORTANDFIND_FIND_MAX_KTH_IN_UNSORTED_ARRAY_H_
