//
// Created by Dan Jiang on 2020/9/8.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SORTANDFIND_FIND_MAX_IN_ASC_DESC_ARRAY_H_
#define ALGORITHMISMYGIRLFRIEND_SORTANDFIND_FIND_MAX_IN_ASC_DESC_ARRAY_H_

int FindMaxInAscDescArray(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SORTANDFIND_FIND_MAX_IN_ASC_DESC_ARRAY_H_
