//
// Created by Dan Jiang on 2020/7/30.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SORTANDFIND_HEAP_SORT_H_
#define ALGORITHMISMYGIRLFRIEND_SORTANDFIND_HEAP_SORT_H_

void HeapSort(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SORTANDFIND_HEAP_SORT_H_
