//
// Created by Dan Jiang on 2020/7/20.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SORT_MERGE_SORT_H_
#define ALGORITHMISMYGIRLFRIEND_SORT_MERGE_SORT_H_

void MergeSort(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SORT_MERGE_SORT_H_
