//
// Created by Dan Jiang on 2020/7/21.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SORTANDFIND_SQRT_BINARY_SEARCH_H_
#define ALGORITHMISMYGIRLFRIEND_SORTANDFIND_SQRT_BINARY_SEARCH_H_

double SqrtBinarySearch(double value, double precision);

#endif //ALGORITHMISMYGIRLFRIEND_SORTANDFIND_SQRT_BINARY_SEARCH_H_
