//
// Created by Dan Jiang on 2020/7/17.
//

#ifndef ALGORITHMISMYGIRLFRIEND_STACKANDQUEUE_IS_POP_ORDER_OF_STACK_H_
#define ALGORITHMISMYGIRLFRIEND_STACKANDQUEUE_IS_POP_ORDER_OF_STACK_H_

bool IsPopOrderOfStack(int *push_array, int *pop_array, int length);

#endif //ALGORITHMISMYGIRLFRIEND_STACKANDQUEUE_IS_POP_ORDER_OF_STACK_H_
