//
// Created by Dan Jiang on 2020/6/12.
//

#ifndef ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_IS_BALANCE_H_
#define ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_IS_BALANCE_H_

#include "binary_tree.h"

bool BinaryTreeIsBalance(BinaryTreeNode *root);

#endif //ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_IS_BALANCE_H_
