//
// Created by Dan Jiang on 2020/6/7.
//

#ifndef ALGORITHMISMYGIRLFRIEND_BINARYTREE_FIND_SUMMARY_PATH_IN_BINARY_TREE_H_
#define ALGORITHMISMYGIRLFRIEND_BINARYTREE_FIND_SUMMARY_PATH_IN_BINARY_TREE_H_

#include "binary_tree.h"

void FindSummaryPathInBT(BinaryTreeNode *root, int expected_sum, std::ostringstream &os);

#endif //ALGORITHMISMYGIRLFRIEND_BINARYTREE_FIND_SUMMARY_PATH_IN_BINARY_TREE_H_
