//
// Created by Dan Jiang on 2020/7/29.
//

#ifndef ALGORITHMISMYGIRLFRIEND_STRING_IS_STRING_REPRESENT_NUMBER_H_
#define ALGORITHMISMYGIRLFRIEND_STRING_IS_STRING_REPRESENT_NUMBER_H_

bool IsStringRepresentNumber(const char *string);

#endif //ALGORITHMISMYGIRLFRIEND_STRING_IS_STRING_REPRESENT_NUMBER_H_
