//
// Created by Dan Jiang on 2020/8/20.
//

#ifndef ALGORITHMISMYGIRLFRIEND_STRING_SIMPLE_COMPRESS_STRING_H_
#define ALGORITHMISMYGIRLFRIEND_STRING_SIMPLE_COMPRESS_STRING_H_

void SimpleCompressString(const char *input, char *output);

#endif //ALGORITHMISMYGIRLFRIEND_STRING_SIMPLE_COMPRESS_STRING_H_
