//
// Created by Dan Jiang on 2020/8/4.
//

#ifndef ALGORITHMISMYGIRLFRIEND_STRING_TRANSLATE_NUMBER_TO_STRING_H_
#define ALGORITHMISMYGIRLFRIEND_STRING_TRANSLATE_NUMBER_TO_STRING_H_

int CountTranslatedNumberToString(int number);

#endif //ALGORITHMISMYGIRLFRIEND_STRING_TRANSLATE_NUMBER_TO_STRING_H_
