//
// Created by Dan Jiang on 2020/7/17.
//

#ifndef ALGORITHMISMYGIRLFRIEND_LINKLIST_CHECK_PALINDROMIC_STRING_IN_LINK_LIST_H_
#define ALGORITHMISMYGIRLFRIEND_LINKLIST_CHECK_PALINDROMIC_STRING_IN_LINK_LIST_H_

#include "link_list.h"

bool CheckPalindromicStringInLinkList(const char *string);

#endif //ALGORITHMISMYGIRLFRIEND_LINKLIST_CHECK_PALINDROMIC_STRING_IN_LINK_LIST_H_
