//
// Created by Dan Jiang on 2020/6/14.
//

#ifndef ALGORITHMISMYGIRLFRIEND_LINKLIST_ENTRY_NODE_OF_LOOP_LINK_LIST_H_
#define ALGORITHMISMYGIRLFRIEND_LINKLIST_ENTRY_NODE_OF_LOOP_LINK_LIST_H_

#include "link_list.h"

ListNode* EntryNodeOfLoopLinkList(ListNode *head);

#endif //ALGORITHMISMYGIRLFRIEND_LINKLIST_ENTRY_NODE_OF_LOOP_LINK_LIST_H_
