//
// Created by Dan Jiang on 2020/6/14.
//

#ifndef ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_FIRST_COMMON_NODE_OF_LINK_LIST_H_
#define ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_FIRST_COMMON_NODE_OF_LINK_LIST_H_

#include "link_list.h"

ListNode* FindFirstCommonNodeOfLinkList(ListNode *first_head, ListNode *second_head);

#endif //ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_FIRST_COMMON_NODE_OF_LINK_LIST_H_
