//
// Created by Dan Jiang on 2020/6/14.
//

#ifndef ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_KTH_TO_TAIL_OF_LINK_LIST_H_
#define ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_KTH_TO_TAIL_OF_LINK_LIST_H_

#include "link_list.h"

ListNode* FindKthToTailOfLinkList(ListNode *head, int k);

#endif //ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_KTH_TO_TAIL_OF_LINK_LIST_H_
