//
// Created by Dan Jiang on 2020/6/14.
//

#ifndef ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_MIDDLE_NODE_OF_LINK_LIST_H_
#define ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_MIDDLE_NODE_OF_LINK_LIST_H_

#include "link_list.h"

ListNode* FindMiddleNodeOfLinkList(ListNode *head);

#endif //ALGORITHMISMYGIRLFRIEND_LINKLIST_FIND_MIDDLE_NODE_OF_LINK_LIST_H_
