//
// Created by Dan Jiang on 2020/6/14.
//

#ifndef ALGORITHMISMYGIRLFRIEND_LINKLIST_REVERSE_LINK_LIST_H_
#define ALGORITHMISMYGIRLFRIEND_LINKLIST_REVERSE_LINK_LIST_H_

#include "link_list.h"

ListNode* ReverseLinkList(ListNode *head);

#endif //ALGORITHMISMYGIRLFRIEND_LINKLIST_REVERSE_LINK_LIST_H_
