//
// Created by Dan Jiang on 2020/7/24.
//

#ifndef ALGORITHMISMYGIRLFRIEND_BITWISE_ADD_WITH_BITWISE_H_
#define ALGORITHMISMYGIRLFRIEND_BITWISE_ADD_WITH_BITWISE_H_

int AddWithBitwise(int num1, int num2);

#endif //ALGORITHMISMYGIRLFRIEND_BITWISE_ADD_WITH_BITWISE_H_
