//
// Created by Dan Jiang on 2020/8/5.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_COUNT_INVERSE_PAIRS_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_COUNT_INVERSE_PAIRS_H_

int CountInversePairs(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_COUNT_INVERSE_PAIRS_H_
