//
// Created by Dan Jiang on 2020/8/9.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_CUTTING_ROPE_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_CUTTING_ROPE_H_

int CuttingRopeDPStates(int length);
int CuttingRopeGreedy(int length);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_CUTTING_ROPE_H_
