//
// Created by Dan Jiang on 2020/7/20.
//

#ifndef ALGORITHMISMYGIRLFRIEND_RECURSIONANDLOOP_FIBONACCI_H_
#define ALGORITHMISMYGIRLFRIEND_RECURSIONANDLOOP_FIBONACCI_H_

int FibonacciRecursion(int n);
int FibonacciLoop(int n);

#endif //ALGORITHMISMYGIRLFRIEND_RECURSIONANDLOOP_FIBONACCI_H_
