//
// Created by Dan Jiang on 2020/8/5.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_FILL_BAG_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_FILL_BAG_H_

void FillBagZeroOne(int items[], int size, int bag_max_weight);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_FILL_BAG_H_
