//
// Created by Dan Jiang on 2020/8/5.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_HAS_STRING_PATH_IN_MATRIX_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_HAS_STRING_PATH_IN_MATRIX_H_

bool HasStringPathInMatrix(char *path, char *matrix, int rows, int columns);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_HAS_STRING_PATH_IN_MATRIX_H_
