//
// Created by Dan Jiang on 2020/8/9.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_LONGEST_NO_DUPLICATE_SUBSTRING_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_LONGEST_NO_DUPLICATE_SUBSTRING_H_

int LongestNoDuplicateSubString(char *string);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_LONGEST_NO_DUPLICATE_SUBSTRING_H_
