//
// Created by Dan Jiang on 2020/8/8.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_LONGEST_INCREASE_SUBSEQUENCE_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_LONGEST_INCREASE_SUBSEQUENCE_H_

int LongestIncreaseSubsequence(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_LONGEST_INCREASE_SUBSEQUENCE_H_
