//
// Created by Dan Jiang on 2020/8/9.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_SUM_SUB_ARRAY_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_SUM_SUB_ARRAY_H_

#include "../common.h"

int MaxSumSubArray(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_SUM_SUB_ARRAY_H_
