//
// Created by Dan Jiang on 2020/8/10.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_PROFIT_OF_STOCK_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_PROFIT_OF_STOCK_H_

#include "../common.h"

int MaxProfitOfStock(int array[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_PROFIT_OF_STOCK_H_
