//
// Created by Dan Jiang on 2020/8/9.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_VALUE_OF_GIFTS_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_VALUE_OF_GIFTS_H_

int MaxValueOfGifts(int matrix[], int rows, int columns);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MAX_VALUE_OF_GIFTS_H_
