//
// Created by Dan Jiang on 2020/8/7.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MOVE_ON_MATRIX_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MOVE_ON_MATRIX_H_

int MoveOnMatrix(int matrix[], int size);
int MoveOnMatrixMemo(int matrix[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_MOVE_ON_MATRIX_H_
