//
// Created by Dan Jiang on 2020/8/5.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_PRINT_8_QUEENS_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_PRINT_8_QUEENS_H_

void Print8Queens();

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_PRINT_8_QUEENS_H_
