//
// Created by Dan Jiang on 2020/8/5.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_SIMPLE_REGULAR_EXPRESSION2_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_SIMPLE_REGULAR_EXPRESSION2_H_

#include "../common.h"

bool SimpleRegularExpression2(char *string, char *pattern);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_SIMPLE_REGULAR_EXPRESSION2_H_
