//
// Created by Dan Jiang on 2020/8/6.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_SIMPLE_ROBOT_MOVE_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_SIMPLE_ROBOT_MOVE_H_

#include "../common.h"

int SimpleRobotMove(int rows, int columns, int threshold);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_SIMPLE_ROBOT_MOVE_H_
