//
// Created by Dan Jiang on 2020/8/7.
//

#ifndef ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_YANG_HUI_TRIANGLE_H_
#define ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_YANG_HUI_TRIANGLE_H_

int YangHuiTriangle(int triangle[], int size);

#endif //ALGORITHMISMYGIRLFRIEND_SKILLANDTHOUGHT_YANG_HUI_TRIANGLE_H_
