//
// Created by Dan Jiang on 2020/7/20.
//

#ifndef ALGORITHMISMYGIRLFRIEND_RECURSIONANDLOOP_PRINT_DICE_PROBABILITY_H_
#define ALGORITHMISMYGIRLFRIEND_RECURSIONANDLOOP_PRINT_DICE_PROBABILITY_H_

void PrintDiceProbabilityRecursion(int number);
void PrintDiceProbabilityLoop(int number);

#endif //ALGORITHMISMYGIRLFRIEND_RECURSIONANDLOOP_PRINT_DICE_PROBABILITY_H_
