//
// Created by Dan Jiang on 2020/6/7.
//

#ifndef ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_CONTAIN_SUB_TREE_H_
#define ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_CONTAIN_SUB_TREE_H_

#include "binary_tree.h"

bool BinaryTreeContainSubTree(BinaryTreeNode *root1, BinaryTreeNode *root2);

#endif //ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_CONTAIN_SUB_TREE_H_
