//
// Created by Dan Jiang on 2020/6/12.
//

#ifndef ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_IS_SYMMETRICAL_H_
#define ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_IS_SYMMETRICAL_H_

#include "binary_tree.h"

bool BinaryTreeIsSymmetrical(BinaryTreeNode *root);

#endif //ALGORITHMISMYGIRLFRIEND_BINARYTREE_BINARY_TREE_IS_SYMMETRICAL_H_
