//
// Created by Dan Jiang on 2020/6/12.
//

#ifndef ALGORITHMISMYGIRLFRIEND_BINARYTREE_GET_BINARY_TREE_INORDER_WALK_NEXT_H_
#define ALGORITHMISMYGIRLFRIEND_BINARYTREE_GET_BINARY_TREE_INORDER_WALK_NEXT_H_

#include "binary_tree.h"

BinaryTreeNode* GetBinaryTreeInorderWalkNext(BinaryTreeNode *node);

#endif //ALGORITHMISMYGIRLFRIEND_BINARYTREE_GET_BINARY_TREE_INORDER_WALK_NEXT_H_
