//
// Created by Dan Jiang on 2020/6/7.
//

#ifndef ALGORITHMISMYGIRLFRIEND_BINARYTREE_IS_POSTORDER_SEQUENCE_OF_BST_H_
#define ALGORITHMISMYGIRLFRIEND_BINARYTREE_IS_POSTORDER_SEQUENCE_OF_BST_H_

bool IsPostorderSequenceOfBST(int *sequence, int length);

#endif //ALGORITHMISMYGIRLFRIEND_BINARYTREE_IS_POSTORDER_SEQUENCE_OF_BST_H_
